name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/content-check'
  schedule:
    - cron: '0 2 * * *' # 每天凌晨2点 (UTC)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build application
        run: make linux-amd64

      - name: Generate release tag and name
        id: generate_tag
        run: |
          TAG="build-$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          name: "Build ${{ steps.generate_tag.outputs.tag }}"
          files: bin/mihomo-linux-amd64
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}